" === VIM SETTINGS ============================================================"
unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

syntax enable
filetype plugin indent on
set hlsearch incsearch ignorecase
set number relativenumber
set wrap linebreak nolist formatoptions=l
set textwidth=80
set encoding=UTF-8

" Make vim save and load the folding of the document each time it loads
" also places the cursor in the last place that it was left.
au BufWinLeave * mkview
au BufWinEnter * silent loadview

" Extend % to match not only braces
runtime macros/matchit.vim

" longer that 80 chars is an erro
match ErrorMsg '\%>80v.\+'
match ErrorMsg '\s\+$'

if $COLORTERM == 'truecolor'
  set termguicolors
endif

let mapleader="\<space>"

"=== PLUGINS =================================================================="
" first thing is install vim-packager:
" git clone https://github.com/kristijanhusak/vim-packager ~/.vim/pack/packager/opt/vim-packager
"
" Second run PackagerInstall inside vim
function! s:packager_init(packager) abort
  call a:packager.add('kristijanhusak/vim-packager', {'type': 'opt'})

  " Navigation and search
  call a:packager.add('junegunn/fzf', { 'do': './install --all && ln -s $(pwd) ~/.fzf'})
  " call a:packager.add('junegunn/fzf.vim', {'do': { -> fzf#install() }})
  call a:packager.add('junegunn/fzf.vim')

  " Language-aware actions, linting & fixing, autocompletion
  call a:packager.add('yegappan/lsp')
  " call a:packager.add('dense-analysis/ale')

  " QOL IDE-like features
  call a:packager.add('907th/vim-auto-save')
  call a:packager.add('jiangmiao/auto-pairs')
  call a:packager.add('itchyny/lightline.vim')
  call a:packager.add('lambdalisue/fern.vim', {'requires': [
        \ 'lambdalisue/fern-git-status.vim',
        \ 'lambdalisue/fern-hijack.vim']})

  " Icons, Colours and syntax highlighting
  call a:packager.add('sheerun/vim-polyglot')
  call a:packager.add('flazz/vim-colorschemes')
  call a:packager.add('ryanoasis/vim-devicons')

  " Misc helper plugins
  call a:packager.add('liuchengxu/vim-which-key')

  " call a:packager.add('vim-autoformat/vim-autoformat')
  call a:packager.add('tpope/vim-commentary')
  call a:packager.add('christoomey/vim-tmux-navigator')
endfunction

packadd vim-packager
call packager#setup(function('s:packager_init'))

"--- WhichKey settings --------------------------------------------------------"
let g:mapleader = "\<Space>"
nnoremap <silent> <leader> :<c-u>WhichKey '<Space>'<CR>
set timeoutlen=200

"--- LSP settings -------------------------------------------------------------"
" Highlights: don't use loclist (used by ALE for diags)
let lspOptions = #{
      \ aleSupport: v:false,
      \ autoComplete: v:true,
      \ autoHighlight: v:true,
      \ autoPopulateDiags: v:true,
      \ completionTextEdit: v:true,
      \ echoSignature: v:true,
      \ diagVirtualTextAlign: 'after',
      \ highlightDiagInline: v:true,
      \ noNewlineInCompletion: v:true,
      \ outlineOnRight: v:true,
      \ outlineWinSize: 70,
      \ showDiagWithSign: v:false,
      \ showDiagWithVirtualText: v:false,
      \ useQuickfixForLocations: v:true,
      \ showInlayHints: v:true,
      \ popupBorderSignatureHelp: v:true,
      \ vsnipSupport: v:true,
      \ }

autocmd VimEnter * call LspOptionsSet(lspOptions)

let lspServers = [
      \ #{ name: 'gopls', filetype: ['go', 'gomod'],  path: 'gopls', args: ['serve'] },
      \ #{ name: 'pylsp', filetype: ['py', 'python'], path: 'pylsp', args: [], syncInit: v:true },
      \ #{ name: 'clangd', filetype: ['c', 'cpp'], path: 'clangd', args: ['--background-index']},
      \ #{ name: 'rustlang', filetype: ['rust'], path: 'rust-analyzer', args: [], syncInit: v:true},
      \ #{ name: 'htmlls', filetype: ['html'], path: 'html-languageserver', args: ['--stdio'], },
      \ #{ name: 'tsserver', filetype: ['javascript', 'typescript'], path: 'typescript-language-server', args: ['--stdio'] },
      \ ]
autocmd VimEnter * call LspAddServer(lspServers)

" Enable auto selection of the fist autocomplete item
augroup LspSetup
  au!
  au User LspAttached set completeopt-=noselect
augroup END
" Disable newline on selecting completion option
inoremap <expr> <CR> pumvisible() ? "\<C-Y>" : "\<CR>"
" Use LSPHover as resolver for K command in normal mode
set keywordprg=:LspHover

"Mappings for most-used functions
nnoremap <leader>la :LspCodeAction<CR>
nnoremap <leader>lA :LspSourceAction<CR>
nnoremap <leader>lr :LspRename<CR>
nnoremap <leader>lR :LspPeekReferences<CR>
nnoremap <leader>li :LspHover<CR>
nnoremap <leader>ld :LspGotoDefinition<CR>
nnoremap <leader>lD :LspGotoDeclaration<CR>
nnoremap <leader>lI :LspGotoImpl<CR>
nnoremap <leader>lp :LspPeekDefinition<CR>
nnoremap <leader>lo :LspDocumentSymbol<CR>
nnoremap <leader>lO :LspOutline<CR>
nnoremap <leader>lc :LspIncomingCalls<CR>
nnoremap <leader>le :LspDiag show<CR>
nnoremap <leader>lw :LspSwitchSourceHeader<CR>

"--- Fuzzy Finder Settings ---------------------------------------------------"
"Mappings for searching within files and buffers
"nnoremap <leader>f :Lines<CR>
nnoremap <leader>F :LspFormat<CR>
nnoremap <leader>ff :Files<CR>
nnoremap <leader>gf :GFiles<CR>
" nnoremap <leader>F :Rg<CR>
nnoremap <leader>b :Buffers<CR>

"Map buffer quick switch keys
nnoremap <leader><Tab> <C-^><CR>
nnoremap <Tab> :Buffers<CR>

"Map Ctrl+P to fzf Files command
nnoremap <silent> <C-p> :Files<CR>

"--- Fern Filetree settings --------------------------------------------------"
let g:webdevicons_enable = 1
let g:webdevicons_enable_nerdtree = 1
" let g:fern#renderer = "devicons"
" let g:fern#default_hidden = 1
" let g:fern#default_exclude = '\%(\.DS_Store\|__pycache__\|.pytest_cache\|.ruff_cache\|.git\)'

nnoremap <leader>e :Fern . -drawer -toggle<CR>

"--- AutoSave settings -------------------------------------------------------"
set noswapfile

"let g:auto_save = 1
let g:auto_save_silent = 1
let g:auto_save_events = ["InsertLeave", "TextChanged", "FocusLost"]

"--- Polyglot settings -------------------------------------------------------"
"let g:polyglot_disabled = ['sensible']

"--- Mistfly statusline settings ---------------------------------------------"
"Don't show the mode as it is present in statusline; always show the statusline
set noshowmode laststatus=2

"--- Vim Test settings -------------------------------------------------------"
" nnoremap <leader>tn :TestNearest<CR>
" nnoremap <leader>tf :TestFile<CR>
" nnoremap <leader>ts :TestSuite<CR>
" nnoremap <leader>tl :TestLast<CR>
"
" let test#strategy = "dispatch"

"--- Vim Autoformat ----------------------------------------------------------"
au BufWritePre * :%s/\s\+$//e " Automatically remove all trailing spaces
" au BufWrite * :Autoformat " Autoformat on save
au BufWrite * :LspFormat " Format on save

"--- Vim Commentary ----------------------------------------------------------"
noremap <leader>/ :Commentary<cr>

"--- Vim Spelling ------------------------------------------------------------"
nnoremap <leader>se :setlocal spell!  spelllang=en<CR>
nnoremap <leader>ss :setlocal spell!  spelllang=es<CR>
nnoremap <leader>sn :setlocal nospell!<CR>

"--- Vim Make ----------------------------------------------------------------"
""" http://vim.wikia.com/wiki/Automatically_open_the_quickfix_window_on_:make
" Automatically open, but do not go to (if there are errors) the quickfix /
" location list window, or close it when is has become empty.
autocmd QuickFixCmdPost [^l]* nested cwindow
autocmd QuickFixCmdPost    l* nested lwindow

"--- Colorscheme settings ----------------------------------------------------"
" Others: tender, gruvbox, atom, nord
colorscheme nord
let g:lightline = { 'colorscheme': 'nord' }

"--- Languages ---------------------------------------------------------------"
"
autocmd FileType javascript setlocal shiftwidth=4 tabstop=4 softtabstop=0 expandtab
